;;; drink-water-quotes.el --- Hydration quotes for drink-water.el -*- lexical-binding: t; -*-

(defvar drink-water-quotes
  '(
    "Water is the driving force of all nature. – Leonardo da Vinci"
    "Thousands have lived without love, not one without water. – W. H. Auden"
    "Pure water is the world's first and foremost medicine. – Slovakian Proverb"
    "Drinking water is essential to a healthy lifestyle. – Stephen Curry"
    "No water, no life. No blue, no green. – Sylvia Earle"
    "Hydration is the key to health."
    "You are not sick, you are thirsty! – F. Batmanghelidj"
    "Water, the hub of life. – Rachel Carson"
    "A glass of water a day keeps fatigue away."
    "Stay hydrated, stay healthy."
    "Water is life's matter and matrix. – Albert Szent-Gyorgyi"
    "When the well is dry, we know the worth of water. – Benjamin Franklin"
    "Drink water, your body will thank you."
    "Hydrate before you're thirsty."
    "Water: the cheapest medicine."
    "Your body is 60% water. Refill it."
    "Every cell in your body needs water."
    "Don't wait, hydrate!"
    "Water is the best natural remedy."
    "A hydrated mind is a healthy mind."
    "Sip by sip, not gulp by gulp."
    "Water is the only drink for a wise man. – Henry David Thoreau"
    "Hydration fuels your energy."
    "Water: the original energy drink."
    "Drink more water than yesterday."
    "Hydrate and conquer."
    "Water is the most neglected nutrient in your diet, but one of the most vital. – Kelly Barton"
    "Start your day with a glass of water."
    "Hydration is not a destination, it's a journey."
    "Water is your body's best friend."
    "A hydrated body is a happy body."
    "Water is the most essential element of life, because without it you can't make coffee."
    "Keep calm and drink water."
    "Water: nature's refreshment."
    "Hydrate to feel great."
    "Drink water and let your soul shine."
    "Water is the most perfect drink."
    "Hydration is self-care."
    "Drink water, be awesome."
    "Water is the foundation of youth."
    "Hydrate for happiness."
    "Water is the answer."
    "Drink water, live longer."
    "Hydration is the first step to wellness."
    "Water is the elixir of life."
    "Stay cool, drink water."
    "Water: the ultimate detox."
    "Hydrate, because you're worth it."
    "Drink water, feel better."
    "Water is the best beauty treatment."
    "Hydrate and thrive."
    "Water is the best way to start and end your day."
    "Drink water, it's a habit worth having."
    "Hydration is the secret to success."
    "Water is the best companion for your journey."
    "Drink water, love life."
    "Hydrate, rejuvenate, celebrate."
    "Water is the best investment in your health."
    "Drink water, stay sharp."
    "Hydration is the foundation of fitness."
    "Water is the best way to refresh your mind and body."
    "Drink water, be unstoppable."
    "Hydrate for a better tomorrow."
    "Water is the best way to show your body some love."
    "Drink water, make it a ritual."
    "Hydration is the key to longevity."
    "Water is the best way to boost your mood."
    "Drink water, it's the smart choice."
    "Hydrate, because your body deserves it."
    "Water is the best way to fuel your dreams."
    "Drink water, it's the ultimate act of self-care.")
  "List of motivational hydration quotes.")

(provide 'drink-water-quotes)
;;; drink-water-quotes.el ends here
